version: '3.8'

services:
    
  rabbitmq:
    container_name: carrot_rabbitmq
    image: 'rabbitmq:3.8.9-management'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=YTmJqsNx2
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_ERLANG_COOKIE=SWLOKODSQBDRPCLNMEQT   
    expose:
      - '5672'
      - '15672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  microservice_interface:
    container_name: carrot_interface
    build: 
      context: ./microservice_interface/
      dockerfile: Dockerfile        
    restart: always
    ports:
      - 5888:5888 
    depends_on:     
      rabbitmq:
        condition: service_healthy

  microservice_sum:
    container_name: carrot_sum
    build: 
      context: ./microservice_sum/
      dockerfile: Dockerfile        
    restart: always
    ports:
      - 5889:5889 
    depends_on:     
      rabbitmq:
        condition: service_healthy



