version: '3.8'

services:
    
  carrot_rabbitmq:
    container_name: carrot_rabbitmq
    image: 'rabbitmq:3.8.9-management'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_ERLANG_COOKIE=SWLOKODSQBDRPCLNMEQT   
    expose:
      - '5672'
      - '15672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  microservice_aa:
    container_name: microservice_aa
    build: 
      context: ./microservice_aa/
      dockerfile: Dockerfile        
    restart: always
    ports:
      - 14000:14000 
    depends_on:     
      carrot_rabbitmq:
        condition: service_healthy

  microservice_bb:
    container_name: microservice_bb
    build: 
      context: ./microservice_bb/
      dockerfile: Dockerfile        
    restart: always
    depends_on:     
      carrot_rabbitmq:
        condition: service_healthy



